server:
  port: 8021

logging:
  config: classpath:conf/log4j2.xml

spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 10.99.6.120
    port: 5672
    username: root
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost